[package]
name = "apalis-workflow"
version = "0.1.0-rc.9"
edition.workspace = true
repository.workspace = true
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
license = "MIT"
description = "A flexible and composable task workflow engine for rust"
publish = true

[features]
default = ["tracing"]
## Enable tracing support
tracing = ["dep:tracing", "apalis-core/tracing"]

[dependencies]
petgraph = { version = "0.8.3", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tower = { version = "0.5", features = ["util"], default-features = false }
apalis-core = { path = "../apalis-core", version = "1.0.0-rc.9", default-features = false, features = [
    "sleep",
    "serde",
] }
apalis-codec = { path = "../utils/apalis-codec" }
futures-util = { version = "0.3.34", features = [
    "sink",
    "async-await",
    "async-await-macro",
    "std",
], default-features = false }
futures-core = { version = "0.3.34", default-features = false }
futures-channel = { version = "0.3.34", features = [
    "sink",
    "std",
], default-features = false }
futures-sink = { version = "0.3.34", default-features = false }
thiserror = "2.0.20"

dashmap = "6.2.1"
tracing = { version = "0.1.44", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
apalis-file-storage = { path = "../utils/apalis-file-storage" }


