[package]
name = "apalis-core"
version = "1.0.0-rc.10"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
edition.workspace = true
repository.workspace = true
license = "MIT"
description = "Core for apalis: simple, extensible multithreaded background processing for Rust"
categories = ["concurrency"]
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
futures-util = { version = "0.3.34", features = [
    "sink",
    "async-await",
    "async-await-macro",
    "std",
], default-features = false }
futures-core = { version = "0.3.34", default-features = false }
futures-channel = { version = "0.3.34", features = [
    "sink",
    "std",
], default-features = false }
futures-sink = { version = "0.3.34", default-features = false }
tower-service = "0.3.3"
tower-layer = "0.3.3"
pin-project = "1"
thiserror = "2.0.20"
rand = { version = "0.10", features = ["std"] }
futures-timer = { version = "3.0.4", optional = true }
tracing = { version = "0.1.44", default-features = false, optional = true }
ulid = { version = "3", optional = true, features = ["uuid"]}
uuid = { version = "1.26.1", features = ["v4", "v5"], optional = true }
dashmap = { version = "6.2.1", default-features = false }


[dependencies.document-features]
version = "0.2"
optional = true


[features]
default = ["sleep", "tracing"]
docsrs = ["dep:document-features"]
## Sleep feature for backends that need to wait
sleep = ["dep:futures-timer"]
## Enable serde support
serde = ["dep:serde", "ulid?/serde", "uuid?/serde"]
## Enable tracing support
tracing = ["dep:tracing"]
## Enable test utilities
test-utils = []
## Enable ulid support for task ids
ulid = ["dep:ulid"]
## Enable uuid support for task ids
uuid = ["dep:uuid"]
# ## Enable the dashmap feature
# dashmap = ["dep:dashmap"]

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
tokio = { version = "1.53.1", features = [
    "macros",
    "rt",
    "sync",
    "rt-multi-thread",
    "signal",
] }
tower = { version = "0.5", features = ["full"] }


