[package]
name = "dynamic-workers"
version = "0.1.0"
license = "MIT"
rust-version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
apalis = { path = "../../apalis" }
serde = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
email-service = { path = "../email-service" }
futures = "0.3"
apalis-file-storage = { path = "../../utils/apalis-file-storage" }
enum_dispatch = "0.3.13"
serde_json = "1"

[dependencies.tracing]
default-features = false
version = "0.1"

[[bin]]
name = "macros"
path = "src/macros.rs"

[[bin]]
name = "generics"
path = "src/generics.rs"

[[bin]]
name = "enum-dispatch"
path = "src/enum_dispatch.rs"

[[bin]]
name = "from-config"
path = "src/from_config.rs"

[lints]
rust.missing_docs = "allow"
