[package]
name = "monitor"
version = "0.1.0"
license = "MIT"
rust-version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
apalis = { path = "../../apalis", features = ["tracing", "opentelemetry"] }
serde = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
email-service = { path = "../email-service" }
apalis-file-storage = { path = "../../utils/apalis-file-storage" }


[dependencies.tracing]
default-features = false
version = "0.1"


